// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WEB_UI.Data;

#nullable disable

namespace WEB_UI.Migrations
{
    [DbContext(typeof(NativaDbContext))]
    partial class NativaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WEB_UI.Models.Entities.Activo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsNacional")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Hectareas")
                        .HasColumnType("decimal(10,4)");

                    b.Property<decimal>("Hidrologia")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("IdDueno")
                        .HasColumnType("int");

                    b.Property<int?>("IdIngeniero")
                        .HasColumnType("int");

                    b.Property<decimal>("Lat")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Lng")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("Topografia")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Vegetacion")
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdDueno");

                    b.HasIndex("IdIngeniero");

                    b.HasIndex("Estado", "FechaRegistro");

                    b.ToTable("Activos");
                });

            modelBuilder.Entity("WEB_UI.Models.Entities.AdjuntoActivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdActivo")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("IdActivo");

                    b.ToTable("AdjuntosActivos");
                });

            modelBuilder.Entity("WEB_UI.Models.Entities.CuentaBancaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Banco")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("IbanCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IbanOfuscado")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<int>("IdDueno")
                        .HasColumnType("int");

                    b.Property<string>("TipoCuenta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Titular")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("IdDueno");

                    b.ToTable("CuentasBancarias");
                });

            modelBuilder.Entity("WEB_UI.Models.Entities.OtpSesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConteoReenvios")
                        .HasColumnType("int");

                    b.Property<DateTime>("Expiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("HashOtp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdSujeto")
                        .HasColumnType("int");

                    b.Property<int>("Intentos")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoReenvio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Usada")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdSujeto");

                    b.ToTable("OtpSesiones");
                });

            modelBuilder.Entity("WEB_UI.Models.Entities.PagoMensual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaEjecucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPlan")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("NumeroPago")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPlan");

                    b.ToTable("PagosMensuales");
                });

            modelBuilder.Entity("WEB_UI.Models.Entities.ParametrosPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreadoPor")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("PctHidrologia")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("PctNacional")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("PctTopografia")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("PctVegetacion")
                        .HasColumnType("decimal(5,4)");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Tope")
                        .HasColumnType("decimal(5,4)");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPor");

                    b.ToTable("ParametrosPago");
                });

            modelBuilder.Entity("WEB_UI.Models.Entities.PlanPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaActivacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("IdActivo")
                        .HasColumnType("int");

                    b.Property<int>("IdIngeniero")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoMensual")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("SnapshotParametrosJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdActivo");

                    b.HasIndex("IdIngeniero");

                    b.ToTable("PlanesPago");
                });

            modelBuilder.Entity("WEB_UI.Models.Entities.Sujeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PasswordResetExpira")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordResetHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Sujetos");
                });

            modelBuilder.Entity("WEB_UI.Models.Entities.Activo", b =>
                {
                    b.HasOne("WEB_UI.Models.Entities.Sujeto", "Dueno")
                        .WithMany("Fincas")
                        .HasForeignKey("IdDueno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WEB_UI.Models.Entities.Sujeto", "Ingeniero")
                        .WithMany()
                        .HasForeignKey("IdIngeniero")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Dueno");

                    b.Navigation("Ingeniero");
                });

            modelBuilder.Entity("WEB_UI.Models.Entities.AdjuntoActivo", b =>
                {
                    b.HasOne("WEB_UI.Models.Entities.Activo", "Activo")
                        .WithMany("Adjuntos")
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activo");
                });

            modelBuilder.Entity("WEB_UI.Models.Entities.CuentaBancaria", b =>
                {
                    b.HasOne("WEB_UI.Models.Entities.Sujeto", "Dueno")
                        .WithMany("CuentasBancarias")
                        .HasForeignKey("IdDueno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dueno");
                });

            modelBuilder.Entity("WEB_UI.Models.Entities.OtpSesion", b =>
                {
                    b.HasOne("WEB_UI.Models.Entities.Sujeto", "Sujeto")
                        .WithMany("OtpSesiones")
                        .HasForeignKey("IdSujeto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sujeto");
                });

            modelBuilder.Entity("WEB_UI.Models.Entities.PagoMensual", b =>
                {
                    b.HasOne("WEB_UI.Models.Entities.PlanPago", "Plan")
                        .WithMany("Pagos")
                        .HasForeignKey("IdPlan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("WEB_UI.Models.Entities.ParametrosPago", b =>
                {
                    b.HasOne("WEB_UI.Models.Entities.Sujeto", "Admin")
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("WEB_UI.Models.Entities.PlanPago", b =>
                {
                    b.HasOne("WEB_UI.Models.Entities.Activo", "Activo")
                        .WithMany("Planes")
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WEB_UI.Models.Entities.Sujeto", "Ingeniero")
                        .WithMany()
                        .HasForeignKey("IdIngeniero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activo");

                    b.Navigation("Ingeniero");
                });

            modelBuilder.Entity("WEB_UI.Models.Entities.Activo", b =>
                {
                    b.Navigation("Adjuntos");

                    b.Navigation("Planes");
                });

            modelBuilder.Entity("WEB_UI.Models.Entities.PlanPago", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("WEB_UI.Models.Entities.Sujeto", b =>
                {
                    b.Navigation("CuentasBancarias");

                    b.Navigation("Fincas");

                    b.Navigation("OtpSesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
