// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nativa.Infrastructure;

#nullable disable

namespace Nativa.Infrastructure.Migrations
{
    [DbContext(typeof(NativaDbContext))]
    [Migration("20260315085530_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Nativa.Domain.Entities.Activo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EsNacional")
                        .HasColumnType("bit");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Hectareas")
                        .HasColumnType("decimal(10, 4)");

                    b.Property<decimal>("Hidrologia")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("IdDueno")
                        .HasColumnType("int");

                    b.Property<int?>("IdIngeniero")
                        .HasColumnType("int");

                    b.Property<decimal>("Lat")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal>("Lng")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("Topografia")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<decimal>("Vegetacion")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id");

                    b.HasIndex("IdDueno");

                    b.HasIndex("IdIngeniero");

                    b.HasIndex("Estado", "FechaRegistro")
                        .HasDatabaseName("IX_Activos_Estado_FechaRegistro");

                    b.ToTable("Activos", (string)null);
                });

            modelBuilder.Entity("Nativa.Domain.Entities.AdjuntoActivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BlobUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdActivo")
                        .HasColumnType("int");

                    b.Property<string>("NombreArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdActivo");

                    b.ToTable("AdjuntosActivos", (string)null);
                });

            modelBuilder.Entity("Nativa.Domain.Entities.CuentaBancaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Banco")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("IbanCompleto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IbanOfuscado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdDueno")
                        .HasColumnType("int");

                    b.Property<string>("TipoCuenta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titular")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdDueno");

                    b.ToTable("CuentasBancarias", (string)null);
                });

            modelBuilder.Entity("Nativa.Domain.Entities.OtpSesion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConteoReenvios")
                        .HasColumnType("int");

                    b.Property<DateTime>("Expiracion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("HashOtp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdSujeto")
                        .HasColumnType("int");

                    b.Property<int>("Intentos")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UltimoReenvio")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Usada")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("IdSujeto");

                    b.ToTable("OtpSesiones", (string)null);
                });

            modelBuilder.Entity("Nativa.Domain.Entities.PagoMensual", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("FechaEjecucion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPlan")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<int>("NumeroPago")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdPlan");

                    b.ToTable("PagosMensuales", (string)null);
                });

            modelBuilder.Entity("Nativa.Domain.Entities.ParametrosPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreadoPor")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("PctHidrologia")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<decimal>("PctNacional")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<decimal>("PctTopografia")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<decimal>("PctVegetacion")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Tope")
                        .HasColumnType("decimal(5, 4)");

                    b.Property<bool>("Vigente")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPor");

                    b.ToTable("ParametrosPagos", (string)null);
                });

            modelBuilder.Entity("Nativa.Domain.Entities.PlanPago", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaActivacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("IdActivo")
                        .HasColumnType("int");

                    b.Property<int>("IdIngeniero")
                        .HasColumnType("int");

                    b.Property<decimal>("MontoMensual")
                        .HasColumnType("decimal(12, 2)");

                    b.Property<string>("SnapshotParametrosJson")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IdActivo");

                    b.HasIndex("IdIngeniero");

                    b.ToTable("PlanesPago", (string)null);
                });

            modelBuilder.Entity("Nativa.Domain.Entities.Sujeto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Sujetos", (string)null);
                });

            modelBuilder.Entity("Nativa.Domain.Entities.Activo", b =>
                {
                    b.HasOne("Nativa.Domain.Entities.Sujeto", "Dueno")
                        .WithMany()
                        .HasForeignKey("IdDueno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nativa.Domain.Entities.Sujeto", "Ingeniero")
                        .WithMany()
                        .HasForeignKey("IdIngeniero")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Dueno");

                    b.Navigation("Ingeniero");
                });

            modelBuilder.Entity("Nativa.Domain.Entities.AdjuntoActivo", b =>
                {
                    b.HasOne("Nativa.Domain.Entities.Activo", "Activo")
                        .WithMany()
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activo");
                });

            modelBuilder.Entity("Nativa.Domain.Entities.CuentaBancaria", b =>
                {
                    b.HasOne("Nativa.Domain.Entities.Sujeto", "Dueno")
                        .WithMany()
                        .HasForeignKey("IdDueno")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dueno");
                });

            modelBuilder.Entity("Nativa.Domain.Entities.OtpSesion", b =>
                {
                    b.HasOne("Nativa.Domain.Entities.Sujeto", "Sujeto")
                        .WithMany()
                        .HasForeignKey("IdSujeto")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Sujeto");
                });

            modelBuilder.Entity("Nativa.Domain.Entities.PagoMensual", b =>
                {
                    b.HasOne("Nativa.Domain.Entities.PlanPago", "Plan")
                        .WithMany()
                        .HasForeignKey("IdPlan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("Nativa.Domain.Entities.ParametrosPago", b =>
                {
                    b.HasOne("Nativa.Domain.Entities.Sujeto", "Creador")
                        .WithMany()
                        .HasForeignKey("CreadoPor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Creador");
                });

            modelBuilder.Entity("Nativa.Domain.Entities.PlanPago", b =>
                {
                    b.HasOne("Nativa.Domain.Entities.Activo", "Activo")
                        .WithMany()
                        .HasForeignKey("IdActivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nativa.Domain.Entities.Sujeto", "Ingeniero")
                        .WithMany()
                        .HasForeignKey("IdIngeniero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activo");

                    b.Navigation("Ingeniero");
                });
#pragma warning restore 612, 618
        }
    }
}
